In [15]:
import requests
import json
import pandas as pd
import numpy as np
import io
from bs4 import BeautifulSoup
# These two things are for Pandas, it widens the notebook and lets us display data easily.
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))
pd.set_option("display.max_rows", None, "display.max_columns", None)

# Minimum Wage By State (2021)

Scrape data

In [125]:
#Data found for minimum wage by state
r = requests.get("https://minimumwage.com/in-your-state/")
#parse
root = BeautifulSoup(r.content)
#find table to make df
table = root.find("table")

Clean data and create DataFrame

In [31]:
#read html table as df
wages = pd.read_html(str(table))
#clean
wages = pd.concat(wages)
#drop all columns except state and wage
wages = wages[["State","Minimum Wage"]]
#final table
wages

                   State Minimum Wage
0                Alabama        $7.25
1                 Alaska       $10.34
2                Arizona       $12.15
3               Arkansas       $11.00
4             California       $14.00
5               Colorado       $12.32
6            Connecticut       $12.00
7               Delaware        $9.25
8   District of Columbia       $15.00
9                Florida        $8.65
10               Georgia        $7.25
11                Hawaii       $10.10
12                 Idaho        $7.25
13              Illinois       $11.00
14               Indiana        $7.25
15                  Iowa        $7.25
16                Kansas        $7.25
17              Kentucky        $7.25
18             Louisiana        $7.25
19                 Maine       $12.15
20              Maryland       $11.75
21         Massachusetts       $13.50
22              Michigan        $9.87
23             Minnesota       $10.08
24           Mississippi        $7.25
25              Missouri       $10.30
26               Montana        $8.75
27              Nebraska        $9.00
28                Nevada        $9.00
29         New Hampshire        $7.25
30            New Jersey       $12.00
31            New Mexico       $10.50
32              New York       $12.50
33        North Carolina        $7.25
34          North Dakota        $7.25
35                  Ohio        $8.80
36              Oklahoma        $7.25
37                Oregon       $12.00
38          Pennsylvania        $7.25
39           Puerto Rico        $7.25
40          Rhode Island       $11.50
41        South Carolina        $7.25
42          South Dakota        $9.45
43             Tennessee        $7.25
44                 Texas        $7.25
45                  Utah        $7.25
46               Vermont       $11.75
47              Virginia        $9.50
48            Washington       $13.69
49         West Virginia        $8.75
50             Wisconsin        $7.25
51               Wyoming        $7.25

# Electoral College Results By State (1980-2020)

Data Scraping

In [124]:
#data for which party each state voted for in presidential elections 
r1 = requests.get("https://en.wikipedia.org/wiki/List_of_United_States_presidential_election_results_by_state")
root1 = BeautifulSoup(r1.content)
table1 = root1.find("table")

Clean data and create DataFrame

In [120]:
#read as table
votes = pd.read_html(str(table1))
votes = pd.concat(votes)
#remove nans at end
votes = votes[:54]
#clean year data
votes[59][0] = 2000
votes[64][0] = 2016
#cut data down to begin in 1980
votes = votes[[0,54,55,56,57,58,59,61,62,63,64,65]]

Label columns

In [123]:
#set years to column values
for columns in votes:
    votes.rename({columns:votes[columns][0]},inplace=True, axis="columns")
votes = votes.drop([0,26,53])
votes

             State 1980 1984 1988 1992 1996 2000 2004 2008 2012 2016 2020
1          Alabama    R    R    R    R    R    R    R    R    R    R    R
2           Alaska    R    R    R    R    R    R    R    R    R    R    R
3          Arizona    R    R    R    R    D    R    R    R    R    R    D
4         Arkansas    R    R    R    D    D    R    R    R    R    R    R
5       California    R    R    R    D    D    D    D    D    D    D    D
6         Colorado    R    R    R    D    R    R    R    D    D    D    D
7      Connecticut    R    R    R    D    D    D    D    D    D    D    D
8         Delaware    R    R    R    D    D    D    D    D    D    D    D
9             D.C.    D    D    D    D    D    D    D    D    D    D    D
10         Florida    R    R    R    R    D    R    R    D    D    R    R
11         Georgia    D    R    R    D    R    R    R    R    R    R    D
12          Hawaii    D    R    D    D    D    D    D    D    D    D    D
13           Idaho    R    R    R    R    R    R    R    R    R    R    R
14        Illinois    R    R    R    D    D    D    D    D    D    D    D
15         Indiana    R    R    R    R    R    R    R    D    R    R    R
16            Iowa    R    R    D    D    D    D    R    D    D    R    R
17          Kansas    R    R    R    R    R    R    R    R    R    R    R
18        Kentucky    R    R    R    D    D    R    R    R    R    R    R
19       Louisiana    R    R    R    D    D    R    R    R    R    R    R
20           Maine    R    R    R    D    D    D    D    D    D    D    D
21        Maryland    D    R    R    D    D    D    D    D    D    D    D
22   Massachusetts    R    R    D    D    D    D    D    D    D    D    D
23        Michigan    R    R    R    D    D    D    D    D    D    R    D
24       Minnesota    D    D    D    D    D    D    D    D    D    D    D
25     Mississippi    R    R    R    R    R    R    R    R    R    R    R
27        Missouri    R    R    R    D    D    R    R    R    R    R    R
28         Montana    R    R    R    D    R    R    R    R    R    R    R
29        Nebraska    R    R    R    R    R    R    R    R    R    R    R
30          Nevada    R    R    R    D    D    R    R    D    D    D    D
31   New Hampshire    R    R    R    D    D    R    D    D    D    D    D
32      New Jersey    R    R    R    D    D    D    D    D    D    D    D
33      New Mexico    R    R    R    D    D    D    R    D    D    D    D
34        New York    R    R    D    D    D    D    D    D    D    D    D
35  North Carolina    R    R    R    R    R    R    R    D    R    R    R
36    North Dakota    R    R    R    R    R    R    R    R    R    R    R
37            Ohio    R    R    R    D    D    R    R    D    D    R    R
38        Oklahoma    R    R    R    R    R    R    R    R    R    R    R
39          Oregon    R    R    D    D    D    D    D    D    D    D    D
40    Pennsylvania    R    R    R    D    D    D    D    D    D    R    D
41    Rhode Island    D    R    D    D    D    D    D    D    D    D    D
42  South Carolina    R    R    R    R    R    R    R    R    R    R    R
43    South Dakota    R    R    R    R    R    R    R    R    R    R    R
44       Tennessee    R    R    R    D    D    R    R    R    R    R    R
45           Texas    R    R    R    R    R    R    R    R    R    R    R
46            Utah    R    R    R    R    R    R    R    R    R    R    R
47         Vermont    R    R    R    D    D    D    D    D    D    D    D
48        Virginia    R    R    R    R    R    R    R    D    D    D    D
49      Washington    R    R    D    D    D    D    D    D    D    D    D
50   West Virginia    D    R    D    D    D    R    R    R    R    R    R
51       Wisconsin    R    R    D    D    D    D    D    D    D    R    D
52         Wyoming    R    R    R    R    R    R    R    R    R    R    R

# Average Temperature By State (2019)

Data Scraping

In [128]:
#data for average 2019 temperature by state
r2 = requests.get("https://worldpopulationreview.com/state-rankings/average-temperatures-by-state")
root2 = BeautifulSoup(r2.content)
table2 = root2.find("table")

Create DataFrame (No cleaning was necessary)

In [127]:
temps = pd.read_html(str(table2))
temps = pd.concat(temps)
temps

             State  Average Temperature
0          Florida                 70.7
1           Hawaii                 70.0
2        Louisiana                 66.4
3            Texas                 64.8
4          Georgia                 63.5
5      Mississippi                 63.4
6          Alabama                 62.8
7   South Carolina                 62.4
8         Arkansas                 60.4
9          Arizona                 60.3
10        Oklahoma                 59.6
11      California                 59.4
12  North Carolina                 59.0
13       Tennessee                 57.6
14        Kentucky                 55.6
15        Delaware                 55.3
16        Virginia                 55.1
17        Missouri                 54.6
18          Kansas                 54.3
19        Maryland                 54.2
20      New Mexico                 53.4
21      New Jersey                 52.7
22   West Virginia                 51.8
23        Illinois                 51.8
24         Indiana                 51.7
25            Ohio                 50.7
26    Rhode Island                 50.1
27          Nevada                 49.9
28     Connecticut                 49.0
29    Pennsylvania                 48.8
30        Nebraska                 48.8
31            Utah                 48.6
32          Oregon                 48.4
33      Washington                 48.3
34   Massachusetts                 47.9
35            Iowa                 47.8
36        New York                 45.4
37    South Dakota                 45.2
38        Colorado                 45.1
39        Michigan                 44.4
40           Idaho                 44.4
41   New Hampshire                 43.8
42       Wisconsin                 43.1
43         Vermont                 42.9
44         Montana                 42.7
45         Wyoming                 42.0
46       Minnesota                 41.2
47           Maine                 41.0
48    North Dakota                 40.4
49          Alaska                 26.6